SET SCHEMA FN71945;

CREATE TABLE STAFF(
  ID INT NOT NULL PRIMARY KEY
);


CREATE TABLE DOCTORS(
    ID_STUFF INT NOT NULL  UNIQUE , --FOREIGN KEY
    NAME VARCHAR(30),
    PHONE_NUMBER VARCHAR(20),
    MAJOR VARCHAR(20),
    OFFICE INT
);


CREATE TABLE NURSES(
    ID_STUFF INT NOT NULL UNIQUE , -- FOREIGN KEY
    NAME VARCHAR(30),
    PHONE_NUMBER VARCHAR(20),
    WORK_POSITION VARCHAR(20)
);

CREATE TABLE MEDICINES(
    ID INT NOT NULL ,
    NAME VARCHAR(30),
    DESCRIPTION VARCHAR(50),
    MANUFACTURER VARCHAR(30)
);

CREATE TABLE PATIENTS(
    EGN CHAR(10) NOT NULL ,
    NAME VARCHAR(20),
    AGE INT,
    DIAGNOSIS VARCHAR(20),
    ROOM_NUMBER INT NOT NULL , --FOREIGN KEY
    DEPT_ID INT NOT NULL --FOREIGN KEY
);


CREATE TABLE ROOMS(
    ROOM_NUMBER INT NOT NULL,
    DEPT_ID INT NOT NULL --FOREIGN KEY
);


CREATE TABLE DEPARTMENTS(
    ID INT NOT NULL ,
    NAME VARCHAR(30),
    DEPARTMENT_HEAD VARCHAR(30)
);


----- Constraints -----
ALTER TABLE MEDICINES ADD CONSTRAINT PK_MEDICINES PRIMARY KEY(ID);

ALTER TABLE PATIENTS ADD CONSTRAINT PK_PATIENTS PRIMARY KEY(EGN);

ALTER TABLE ROOMS ADD CONSTRAINT PK_ROOMS PRIMARY KEY(ROOM_NUMBER);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENTS PRIMARY KEY(ID);

ALTER TABLE DOCTORS ADD CONSTRAINT FK_DOCTORS_STAFF FOREIGN KEY(ID_STUFF) REFERENCES STAFF(ID);

ALTER TABLE NURSES ADD CONSTRAINT FK_NURSES_STAFF FOREIGN KEY (ID_STUFF) REFERENCES STAFF(ID);

ALTER TABLE PATIENTS ADD CONSTRAINT FK_PATIENTS_ROOMS FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOMS(ROOM_NUMBER);

ALTER TABLE PATIENTS ADD CONSTRAINT FK_PATIENTS_DEPARTMENTS FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(ID);

ALTER TABLE ROOMS ADD CONSTRAINT  FK_ROOMS_DEPARTMENTS FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(ID);

ALTER TABLE STAFF ADD CONSTRAINT CK_ID CHECK ( ID > 0 );

ALTER TABLE DOCTORS ADD CONSTRAINT CK_OFFICE CHECK ( OFFICE >0 );

ALTER TABLE MEDICINES ADD CONSTRAINT CK_MEDICINES CHECK ( ID > 0 );

ALTER TABLE PATIENTS ADD CONSTRAINT  CK_PATIENTS CHECK ( AGE >0 );

ALTER TABLE DEPARTMENTS ADD CONSTRAINT CK_DEPARTMENTS CHECK ( ID > 0 );