SET SCHEMA FN71945;

CREATE OR REPLACE FUNCTION DOCTORS_ID(V_ID_DOCTORS INT)
RETURNS TABLE (NAME VARCHAR(50),MAJOR VARCHAR(20),OFFICE INT)
RETURN
SELECT NAME, MAJOR,OFFICE
FROM DOCTORS
WHERE ID_STUFF=V_ID_DOCTORS;

SELECT *
FROM TABLE(FN71945.DOCTORS_ID(102));

CREATE FUNCTION PATIENTS_AGE(V_EGN CHAR(10))
RETURNS INT
RETURN
SELECT AGE
FROM PATIENTS
WHERE EGN=V_EGN;

SELECT NAME, FN71945.PATIENTS_AGE('7512235632')
FROM PATIENTS
WHERE EGN='7512235632';

