SET SCHEMA FN71945;

SELECT * FROM FN71945.PATIENT_DEPARTMENT_INFO;
SELECT * FROM PATIENTS;

CREATE TRIGGER UPDATE_VIEW1
    INSTEAD OF UPDATE ON PATIENT_DEPARTMENT_INFO
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
     UPDATE PATIENTS
     SET NAME = N.NAME
     WHERE NAME = O.NAME;

UPDATE PATIENTS
SET NAME = 'ELENA GEORGIEVA'
WHERE EGN = '7611243654';

UPDATE PATIENTS
SET NAME = 'TANYA DIMITROVA'
WHERE EGN = '7611243654';

-- TRIG AND PROC

DROP TRIGGER UPD_DIAG_PAT_TRIGG;

CREATE OR REPLACE TRIGGER UPD_DIAG_PAT_TRIGG
    AFTER UPDATE OF DIAGNOSIS ON FN71945.PATIENTS
    REFERENCING NEW AS N
    FOR EACH ROW
      WHEN(N.DIAGNOSIS IS NULL)
      CALL FN71945.PATIENTS_DIAGNOSIS_NULL();

SELECT * FROM PATIENTS;

UPDATE PATIENTS
SET DIAGNOSIS= 'HIGH BLOOD PRESSURE'
WHERE EGN='7710254589';

UPDATE PATIENTS
SET DIAGNOSIS= NULL
WHERE EGN='7710254589';