SET SCHEMA FN71945;

CREATE VIEW PATIENT_DEPARTMENT_INFO
AS
SELECT P.NAME,P.DIAGNOSIS,D.DEPARTMENT_HEAD,D.ID
FROM PATIENTS P , DEPARTMENTS D
WHERE P.DEPT_ID = DEPT_ID

SELECT * FROM PATIENT_DEPARTMENT_INFO;


CREATE VIEW PATIENTS_ROOMS_INFO
AS
SELECT P.NAME,P.EGN,R.ROOM_NUMBER
FROM PATIENTS P , ROOMS R
WHERE P.ROOM_NUMBER = R.ROOM_NUMBER;


SELECT * FROM PATIENTS_ROOMS_INFO;